name: Build
on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]
  workflow_dispatch:
jobs:
  linux:
    uses: externpro/externpro/.github/workflows/build-linux.yml@25.05
    with:
      cmake-workflow-preset: Linux
      runon: ubuntu-latest
    secrets: inherit
  linux-arm64:
    uses: externpro/externpro/.github/workflows/build-linux.yml@25.05
    with:
      cmake-workflow-preset: Linux
      runon: ubuntu-24.04-arm
    secrets: inherit
  windows:
    uses: externpro/externpro/.github/workflows/build-windows.yml@25.05
    with:
      cmake-workflow-preset: Windows
    secrets: inherit
